### ISSUE TITLE
Python3 Compatibility

### ISSUE THREAD

**Issue by printfinn** [loblab/rfask#1]
Dude, this is nice!
I used your code to complete my garage door remote control webapp.
While I met some little issues,
1. In Python 3, print is now a function, and followed by parenthesis ( ).
2. There seems to be some problem with the argument 'VERSION',  I have to delete this parameter while calling the function. 

After these two fixes, it works perfectly on Python 3.
Thanks so much for your code, after all!

**Comment by loblab** [comment]
Thanks for your feedback.

Python3 is supported now (in ver 0.7), and argument 'VERSION' is also supported.

argparse moved argument 'version' out from constructor. Just add it manually.

```python
parser.add_argument('-v', '--version', action='version', version=VERSION)
 ```
